### ISSUE TITLE
compil

### ISSUE THREAD

**Issue by eysho** [wolfie/Kura-MUD#18]
close pls

**Comment by eysho** [comment]
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
        at mud.MUDServer.loadRaces(MUDServer.java:22005)
        at mud.MUDServer.setup(MUDServer.java:959)
        at mud.MUDServer.init(MUDServer.java:737)
        at mud.MUDServer.main(MUDServer.java:695)
Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 4 more
